name: Fix Dockerhub
on:
  workflow_dispatch:
jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Reload Docker
        run: |
          docker pull denisa/super-linter:v5.0.0
          docker pull denisa/super-linter:slim-v5.0.0
          docker pull denisa/super-linter:v4.10.1
          docker pull denisa/super-linter:slim-v4.10.1
          docker tag denisa/super-linter:v5.0.0 denisa/super-linter:v5
          docker tag denisa/super-linter:slim-v5.0.0 denisa/super-linter:slim-v5
          docker tag denisa/super-linter:v4.10.1 denisa/super-linter:v4
          docker tag denisa/super-linter:slim-v4.10.1 denisa/super-linter:slim-v4
          docker push denisa/super-linter:v5
          docker push denisa/super-linter:slim-v5
          docker push denisa/super-linter:v4
          docker push denisa/super-linter:slim-v4

